# Data Pre-processing

## Melbourne Airbnb Open Data
## Source : Kaggle

In [5]:
import numpy as np
import pandas as pd

In [12]:
airbnb = pd.read_csv("D:\AirbnbMelb.csv")
airbnb

,id,host_id,property_type,price,weekly_price,monthly_price,security_deposit,cleaning_fee,extra_people,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,review_scores_rating
0,9835,33057,House,60,NaN,NaN,NaN,NaN,22,1,365,30,60,90,365,90.0
1,10803,38901,Apartment,35,200.0,803.0,0.0,9.0,15,3,45,4,9,33,213,87.0
2,12936,50121,Apartment,159,1253.0,4452.0,450.0,100.0,28,3,28,10,26,51,326,94.0
3,15246,59786,House,50,250.0,920.0,200.0,15.0,20,2,200,0,0,0,0,94.0
4,16760,65090,House,69,400.0,1900.0,NaN,15.0,20,1,90,2,30,60,328,90.0
5,38271,164193,Apartment,98,540.0,NaN,0.0,0.0,30,1,14,12,27,57,328,97.0
6,41836,182833,House,50,335.0,1400.0,NaN,10.0,20,7,365,0,0,0,0,94.0
7,43414,189682,Apartment,100,NaN,NaN,1000.0,30.0,25,1,90,5,11,11,11,93.0
8,43429,189684,Apartment,98,535.0,NaN,500.0,40.0,0,2,365,7,25,35,310,97.0
9,44082,193031,House,60,413.0,1540.0,0.0,29.0,20,3,730,1,5,35,310,99.0
10,47100,212071,Apartment,98,800.0,NaN,200.0,80.0,20,4,30,13,13,18,22,98.0
11,50492,50121,Apartment,190,1743.0,5572.0,500.0,110.0,0,3,28,10,22,44,316,97.0
12,51592,190879,Loft,228,1575.0,5100.0,250.0,40.0,40,2,90,13,39,56,331,99.0
13,58055,277353,House,46,320.0,1150.0,NaN,NaN,12,2,730,21,28,28,278,85.0
14,62606,277353,House,50,300.0,1000.0,NaN,NaN,11,2,730,15,23,53,328,84.0
15,65432,277353,House,43,300.0,1100.0,NaN,NaN,0,2,60,5,32,62,337,81.0
16,66754,50121,Apartment,138,1183.0,4172.0,450.0,100.0,28,3,28,11,19,49,324,95.0
17,67211,326880,Apartment,42,NaN,NaN,NaN,NaN,0,2,30,10,30,55,330,95.0
18,68036,336319,House,161,NaN,NaN,NaN,NaN,0,5,9,0,0,0,128,98.0
19,68411,334095,House,300,NaN,NaN,NaN,NaN,0,1,730,0,0,0,0,NaN
20,68482,59786,House,140,920.0,3000.0,300.0,50.0,30,5,365,0,0,0,0,95.0
21,69421,347754,Apartment,180,1000.0,4000.0,NaN,50.0,50,2,90,30,60,90,365,100.0
22,70004,193031,House,60,343.0,1260.0,0.0,29.0,0,2,300,27,38,68,343,100.0
23,70328,356006,Townhouse,68,385.0,1500.0,200.0,NaN,20,1,14,24,44,74,349,98.0
24,71156,318900,Apartment,60,200.0,800.0,0.0,20.0,20,3,5,0,0,0,0,95.0
25,72576,376675,House,120,NaN,NaN,0.0,0.0,10,3,31,17,36,63,243,99.0
26,74324,390761,Townhouse,228,2437.0,8648.0,5503.0,142.0,24,30,300,0,0,0,271,96.0
27,74548,392505,Apartment,64,NaN,NaN,0.0,0.0,0,2,30,0,12,18,283,97.0
28,74715,392594,House,48,300.0,NaN,NaN,NaN,10,2,30,0,0,26,106,94.0
29,74959,395864,Townhouse,96,665.0,NaN,0.0,30.0,0,2,31,21,51,76,351,99.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22865,30575199,185076876,House,228,NaN,NaN,800.0,165.0,30,2,60,27,57,87,87,NaN
22866,30576948,27396677,House,80,NaN,NaN,0.0,0.0,20,1,1125,3,33,63,114,NaN
22867,30577049,217343588,Apartment,138,NaN,NaN,200.0,69.0,20,1,1125,27,54,84,174,NaN
22868,30577491,39185276,Townhouse,50,NaN,NaN,NaN,NaN,0,3,1125,6,36,66,156,NaN
22869,30577799,39420239,Apartment,58,NaN,NaN,NaN,NaN,0,3,1125,21,51,81,171,NaN
22870,30578011,39420239,Apartment,76,NaN,NaN,NaN,NaN,0,3,1125,10,40,70,160,NaN
22871,30578581,23405787,House,169,NaN,NaN,500.0,90.0,25,2,1125,30,60,90,365,NaN
22872,30578762,212741130,Apartment,148,NaN,NaN,350.0,90.0,25,1,1125,28,58,88,88,NaN
22873,30578960,126914673,House,30,NaN,NaN,NaN,NaN,0,7,1125,22,52,82,82,NaN
22874,30579138,229390285,House,40,NaN,NaN,NaN,NaN,0,1,1125,22,52,82,172,NaN
22875,30582317,127991555,Apartment,61,NaN,NaN,NaN,29.0,0,2,1125,10,10,10,10,NaN
22876,30587155,61455951,House,69,NaN,NaN,NaN,NaN,0,1,1125,25,55,85,175,NaN
22877,30588253,225492121,Apartment,64,NaN,NaN,250.0,18.0,15,2,4,22,52,82,82,NaN
22878,30589214,191529248,Townhouse,198,NaN,NaN,NaN,NaN,0,2,1125,13,20,50,50,NaN
22879,30589523,69874002,Townhouse,43,NaN,NaN,NaN,50.0,0,4,1125,3,3,3,3,NaN
22880,30590069,179249614,Apartment,71,NaN,NaN,NaN,NaN,0,1,1125,12,42,72,162,NaN
22881,30590430,9020997,House,79,NaN,NaN,500.0,0.0,20,1,1125,27,56,56,56,NaN
22882,30590506,894925,Apartment,84,NaN,NaN,0.0,30.0,10,2,1125,27,41,71,346,NaN
22883,30590632,44912736,House,114,NaN,NaN,NaN,NaN,0,1,1125,5,35,65,340,NaN
22884,30590791,115126017,Apartment,75,NaN,NaN,138.0,15.0,0,1,1125,23,48,74,74,NaN
22885,30591274,229470515,House,50,NaN,NaN,NaN,NaN,0,1,1125,14,44,74,164,NaN
22886,30591343,9020997,House,79,NaN,NaN,500.0,0.0,20,1,1125,27,56,56,56,NaN
22887,30591408,154630235,Serviced apartment,127,NaN,NaN,300.0,55.0,20,3,31,25,25,25,25,NaN
22888,30592088,92403349,Apartment,84,NaN,NaN,NaN,NaN,0,1,12,20,41,62,62,NaN
22889,30592128,26129617,Apartment,30,NaN,NaN,NaN,0.0,0,2,1125,29,29,29,29,NaN
22890,30592332,229206629,Apartment,55,NaN,NaN,NaN,NaN,0,1,90,22,52,82,82,NaN
22891,30592345,150660631,House,129,NaN,NaN,NaN,NaN,0,1,1125,30,60,90,365,NaN
22892,30592362,130394565,Guesthouse,53,NaN,NaN,NaN,NaN,0,3,1125,0,5,15,15,NaN
22893,30592590,22630928,Apartment,130,NaN,NaN,250.0,130.0,0,7,750,14,44,74,349,NaN
22894,30593623,38305445,Apartment,179,NaN,NaN,NaN,NaN,0,1,14,15,44,68,68,NaN

In [13]:
#Mengidentifikasi Missing Value

np.sum(airbnb.isnull())

id                          0
host_id                     0
property_type               0
price                       0
weekly_price            20371
monthly_price           21004
security_deposit         7494
cleaning_fee             5646
extra_people                0
minimum_nights              0
maximum_nights              0
availability_30             0
availability_60             0
availability_90             0
availability_365            0
review_scores_rating     5706
dtype: int64

In [14]:
# Statdes pada data Airbnb

airbnb.describe()

,id,host_id,price,weekly_price,monthly_price,security_deposit,cleaning_fee,extra_people,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,review_scores_rating
count,2.289500e+04,2.289500e+04,22895.000000,2524.000000,1891.000000,15401.000000,17249.000000,22895.000000,22895.000000,2.289500e+04,22895.000000,22895.000000,22895.000000,22895.000000,17189.000000
mean,1.869883e+07,7.083412e+07,148.004368,906.976228,3234.346906,316.578469,65.741144,12.970823,4.059314,5.141727e+03,10.247827,23.787770,39.203363,135.147063,94.182791
std,8.141522e+06,6.471893e+07,210.883253,821.223782,2808.092144,479.172431,57.951446,20.952192,25.883257,6.609042e+05,10.461592,21.426187,32.998461,133.326188,8.567504
min,9.835000e+03,9.082000e+03,0.000000,91.000000,400.000000,0.000000,0.000000,0.000000,1.000000,1.000000e+00,0.000000,0.000000,0.000000,0.000000,20.000000
25%,1.287570e+07,1.728005e+07,71.000000,450.000000,1700.000000,133.000000,25.000000,0.000000,1.000000,5.900000e+01,0.000000,0.000000,0.000000,4.000000,92.000000
50%,2.026177e+07,4.801411e+07,111.000000,750.000000,2800.000000,200.000000,59.000000,0.000000,2.000000,1.125000e+03,7.000000,21.000000,38.000000,88.000000,97.000000
75%,2.495525e+07,1.143842e+08,165.000000,1066.000000,3912.500000,400.000000,90.000000,20.000000,3.000000,1.125000e+03,19.000000,43.000000,70.000000,276.000000,100.000000
max,3.059362e+07,2.294705e+08,12624.000000,11536.000000,54258.000000,6950.000000,867.000000,421.000000,1125.000000,1.000000e+08,30.000000,60.000000,90.000000,365.000000,100.000000

In [15]:
# Filling Missing Value with Mean

airbnb["weekly_price"]=airbnb["weekly_price"].fillna((airbnb["weekly_price"].mean()))
np.sum(airbnb.isnull())

id                          0
host_id                     0
property_type               0
price                       0
weekly_price                0
monthly_price           21004
security_deposit         7494
cleaning_fee             5646
extra_people                0
minimum_nights              0
maximum_nights              0
availability_30             0
availability_60             0
availability_90             0
availability_365            0
review_scores_rating     5706
dtype: int64

In [17]:
# Filling Missing Value with Mean

airbnb["monthly_price"]=airbnb["monthly_price"].fillna((airbnb["monthly_price"].mean()))
airbnb["security_deposit"]=airbnb["security_deposit"].fillna((airbnb["security_deposit"].mean()))
airbnb["cleaning_fee"]=airbnb["cleaning_fee"].fillna((airbnb["cleaning_fee"].mean()))
airbnb["review_scores_rating"]=airbnb["review_scores_rating"].fillna((airbnb["review_scores_rating"].mean()))
np.sum(airbnb.isnull())

id                      0
host_id                 0
property_type           0
price                   0
weekly_price            0
monthly_price           0
security_deposit        0
cleaning_fee            0
extra_people            0
minimum_nights          0
maximum_nights          0
availability_30         0
availability_60         0
availability_90         0
availability_365        0
review_scores_rating    0
dtype: int64

In [18]:
airbnb

,id,host_id,property_type,price,weekly_price,monthly_price,security_deposit,cleaning_fee,extra_people,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,review_scores_rating
0,9835,33057,House,60,906.976228,3234.346906,316.578469,65.741144,22,1,365,30,60,90,365,90.000000
1,10803,38901,Apartment,35,200.000000,803.000000,0.000000,9.000000,15,3,45,4,9,33,213,87.000000
2,12936,50121,Apartment,159,1253.000000,4452.000000,450.000000,100.000000,28,3,28,10,26,51,326,94.000000
3,15246,59786,House,50,250.000000,920.000000,200.000000,15.000000,20,2,200,0,0,0,0,94.000000
4,16760,65090,House,69,400.000000,1900.000000,316.578469,15.000000,20,1,90,2,30,60,328,90.000000
5,38271,164193,Apartment,98,540.000000,3234.346906,0.000000,0.000000,30,1,14,12,27,57,328,97.000000
6,41836,182833,House,50,335.000000,1400.000000,316.578469,10.000000,20,7,365,0,0,0,0,94.000000
7,43414,189682,Apartment,100,906.976228,3234.346906,1000.000000,30.000000,25,1,90,5,11,11,11,93.000000
8,43429,189684,Apartment,98,535.000000,3234.346906,500.000000,40.000000,0,2,365,7,25,35,310,97.000000
9,44082,193031,House,60,413.000000,1540.000000,0.000000,29.000000,20,3,730,1,5,35,310,99.000000
10,47100,212071,Apartment,98,800.000000,3234.346906,200.000000,80.000000,20,4,30,13,13,18,22,98.000000
11,50492,50121,Apartment,190,1743.000000,5572.000000,500.000000,110.000000,0,3,28,10,22,44,316,97.000000
12,51592,190879,Loft,228,1575.000000,5100.000000,250.000000,40.000000,40,2,90,13,39,56,331,99.000000
13,58055,277353,House,46,320.000000,1150.000000,316.578469,65.741144,12,2,730,21,28,28,278,85.000000
14,62606,277353,House,50,300.000000,1000.000000,316.578469,65.741144,11,2,730,15,23,53,328,84.000000
15,65432,277353,House,43,300.000000,1100.000000,316.578469,65.741144,0,2,60,5,32,62,337,81.000000
16,66754,50121,Apartment,138,1183.000000,4172.000000,450.000000,100.000000,28,3,28,11,19,49,324,95.000000
17,67211,326880,Apartment,42,906.976228,3234.346906,316.578469,65.741144,0,2,30,10,30,55,330,95.000000
18,68036,336319,House,161,906.976228,3234.346906,316.578469,65.741144,0,5,9,0,0,0,128,98.000000
19,68411,334095,House,300,906.976228,3234.346906,316.578469,65.741144,0,1,730,0,0,0,0,94.182791
20,68482,59786,House,140,920.000000,3000.000000,300.000000,50.000000,30,5,365,0,0,0,0,95.000000
21,69421,347754,Apartment,180,1000.000000,4000.000000,316.578469,50.000000,50,2,90,30,60,90,365,100.000000
22,70004,193031,House,60,343.000000,1260.000000,0.000000,29.000000,0,2,300,27,38,68,343,100.000000
23,70328,356006,Townhouse,68,385.000000,1500.000000,200.000000,65.741144,20,1,14,24,44,74,349,98.000000
24,71156,318900,Apartment,60,200.000000,800.000000,0.000000,20.000000,20,3,5,0,0,0,0,95.000000
25,72576,376675,House,120,906.976228,3234.346906,0.000000,0.000000,10,3,31,17,36,63,243,99.000000
26,74324,390761,Townhouse,228,2437.000000,8648.000000,5503.000000,142.000000,24,30,300,0,0,0,271,96.000000
27,74548,392505,Apartment,64,906.976228,3234.346906,0.000000,0.000000,0,2,30,0,12,18,283,97.000000
28,74715,392594,House,48,300.000000,3234.346906,316.578469,65.741144,10,2,30,0,0,26,106,94.000000
29,74959,395864,Townhouse,96,665.000000,3234.346906,0.000000,30.000000,0,2,31,21,51,76,351,99.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22865,30575199,185076876,House,228,906.976228,3234.346906,800.000000,165.000000,30,2,60,27,57,87,87,94.182791
22866,30576948,27396677,House,80,906.976228,3234.346906,0.000000,0.000000,20,1,1125,3,33,63,114,94.182791
22867,30577049,217343588,Apartment,138,906.976228,3234.346906,200.000000,69.000000,20,1,1125,27,54,84,174,94.182791
22868,30577491,39185276,Townhouse,50,906.976228,3234.346906,316.578469,65.741144,0,3,1125,6,36,66,156,94.182791
22869,30577799,39420239,Apartment,58,906.976228,3234.346906,316.578469,65.741144,0,3,1125,21,51,81,171,94.182791
22870,30578011,39420239,Apartment,76,906.976228,3234.346906,316.578469,65.741144,0,3,1125,10,40,70,160,94.182791
22871,30578581,23405787,House,169,906.976228,3234.346906,500.000000,90.000000,25,2,1125,30,60,90,365,94.182791
22872,30578762,212741130,Apartment,148,906.976228,3234.346906,350.000000,90.000000,25,1,1125,28,58,88,88,94.182791
22873,30578960,126914673,House,30,906.976228,3234.346906,316.578469,65.741144,0,7,1125,22,52,82,82,94.182791
22874,30579138,229390285,House,40,906.976228,3234.346906,316.578469,65.741144,0,1,1125,22,52,82,172,94.182791
22875,30582317,127991555,Apartment,61,906.976228,3234.346906,316.578469,29.000000,0,2,1125,10,10,10,10,94.182791
22876,30587155,61455951,House,69,906.976228,3234.346906,316.578469,65.741144,0,1,1125,25,55,85,175,94.182791
22877,30588253,225492121,Apartment,64,906.976228,3234.346906,250.000000,18.000000,15,2,4,22,52,82,82,94.182791
22878,30589214,191529248,Townhouse,198,906.976228,3234.346906,316.578469,65.741144,0,2,1125,13,20,50,50,94.182791
22879,30589523,69874002,Townhouse,43,906.976228,3234.346906,316.578469,50.000000,0,4,1125,3,3,3,3,94.182791
22880,30590069,179249614,Apartment,71,906.976228,3234.346906,316.578469,65.741144,0,1,1125,12,42,72,162,94.182791
22881,30590430,9020997,House,79,906.976228,3234.346906,500.000000,0.000000,20,1,1125,27,56,56,56,94.182791
22882,30590506,894925,Apartment,84,906.976228,3234.346906,0.000000,30.000000,10,2,1125,27,41,71,346,94.182791
22883,30590632,44912736,House,114,906.976228,3234.346906,316.578469,65.741144,0,1,1125,5,35,65,340,94.182791
22884,30590791,115126017,Apartment,75,906.976228,3234.346906,138.000000,15.000000,0,1,1125,23,48,74,74,94.182791
22885,30591274,229470515,House,50,906.976228,3234.346906,316.578469,65.741144,0,1,1125,14,44,74,164,94.182791
22886,30591343,9020997,House,79,906.976228,3234.346906,500.000000,0.000000,20,1,1125,27,56,56,56,94.182791
22887,30591408,154630235,Serviced apartment,127,906.976228,3234.346906,300.000000,55.000000,20,3,31,25,25,25,25,94.182791
22888,30592088,92403349,Apartment,84,906.976228,3234.346906,316.578469,65.741144,0,1,12,20,41,62,62,94.182791
22889,30592128,26129617,Apartment,30,906.976228,3234.346906,316.578469,0.000000,0,2,1125,29,29,29,29,94.182791
22890,30592332,229206629,Apartment,55,906.976228,3234.346906,316.578469,65.741144,0,1,90,22,52,82,82,94.182791
22891,30592345,150660631,House,129,906.976228,3234.346906,316.578469,65.741144,0,1,1125,30,60,90,365,94.182791
22892,30592362,130394565,Guesthouse,53,906.976228,3234.346906,316.578469,65.741144,0,3,1125,0,5,15,15,94.182791
22893,30592590,22630928,Apartment,130,906.976228,3234.346906,250.000000,130.000000,0,7,750,14,44,74,349,94.182791
22894,30593623,38305445,Apartment,179,906.976228,3234.346906,316.578469,65.741144,0,1,14,15,44,68,68,94.182791

In [19]:
# Mengatasi Outlier

from scipy import stats
z = np.abs(stats.zscore(airbnb._get_numeric_data()))
print(z)
airbnb= airbnb[(z<3).all(axis=1)]
print(airbnb.shape)

[[2.29556612 1.09400148 0.41732233 ... 1.53939742 1.72402707 0.56346837]
 [2.29544722 1.09391118 0.53587392 ... 0.18799357 0.58394108 0.96760163]
 [2.29518523 1.09373781 0.05214199 ... 0.35749832 1.43150501 0.02462402]
 ...
 [1.46088065 0.92031421 0.45051677 ... 0.73348547 0.90117094 0.        ]
 [1.46090866 0.74482443 0.08537786 ... 1.05451574 1.60401802 0.        ]
 [1.46103554 0.50262544 0.14698327 ... 0.87268511 0.50364096 0.        ]]
(21233, 16)

In [20]:
airbnb

,id,host_id,property_type,price,weekly_price,monthly_price,security_deposit,cleaning_fee,extra_people,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,review_scores_rating
0,9835,33057,House,60,906.976228,3234.346906,316.578469,65.741144,22,1,365,30,60,90,365,90.000000
2,12936,50121,Apartment,159,1253.000000,4452.000000,450.000000,100.000000,28,3,28,10,26,51,326,94.000000
3,15246,59786,House,50,250.000000,920.000000,200.000000,15.000000,20,2,200,0,0,0,0,94.000000
4,16760,65090,House,69,400.000000,1900.000000,316.578469,15.000000,20,1,90,2,30,60,328,90.000000
5,38271,164193,Apartment,98,540.000000,3234.346906,0.000000,0.000000,30,1,14,12,27,57,328,97.000000
6,41836,182833,House,50,335.000000,1400.000000,316.578469,10.000000,20,7,365,0,0,0,0,94.000000
7,43414,189682,Apartment,100,906.976228,3234.346906,1000.000000,30.000000,25,1,90,5,11,11,11,93.000000
8,43429,189684,Apartment,98,535.000000,3234.346906,500.000000,40.000000,0,2,365,7,25,35,310,97.000000
9,44082,193031,House,60,413.000000,1540.000000,0.000000,29.000000,20,3,730,1,5,35,310,99.000000
10,47100,212071,Apartment,98,800.000000,3234.346906,200.000000,80.000000,20,4,30,13,13,18,22,98.000000
12,51592,190879,Loft,228,1575.000000,5100.000000,250.000000,40.000000,40,2,90,13,39,56,331,99.000000
13,58055,277353,House,46,320.000000,1150.000000,316.578469,65.741144,12,2,730,21,28,28,278,85.000000
14,62606,277353,House,50,300.000000,1000.000000,316.578469,65.741144,11,2,730,15,23,53,328,84.000000
15,65432,277353,House,43,300.000000,1100.000000,316.578469,65.741144,0,2,60,5,32,62,337,81.000000
16,66754,50121,Apartment,138,1183.000000,4172.000000,450.000000,100.000000,28,3,28,11,19,49,324,95.000000
17,67211,326880,Apartment,42,906.976228,3234.346906,316.578469,65.741144,0,2,30,10,30,55,330,95.000000
18,68036,336319,House,161,906.976228,3234.346906,316.578469,65.741144,0,5,9,0,0,0,128,98.000000
19,68411,334095,House,300,906.976228,3234.346906,316.578469,65.741144,0,1,730,0,0,0,0,94.182791
20,68482,59786,House,140,920.000000,3000.000000,300.000000,50.000000,30,5,365,0,0,0,0,95.000000
21,69421,347754,Apartment,180,1000.000000,4000.000000,316.578469,50.000000,50,2,90,30,60,90,365,100.000000
22,70004,193031,House,60,343.000000,1260.000000,0.000000,29.000000,0,2,300,27,38,68,343,100.000000
23,70328,356006,Townhouse,68,385.000000,1500.000000,200.000000,65.741144,20,1,14,24,44,74,349,98.000000
25,72576,376675,House,120,906.976228,3234.346906,0.000000,0.000000,10,3,31,17,36,63,243,99.000000
27,74548,392505,Apartment,64,906.976228,3234.346906,0.000000,0.000000,0,2,30,0,12,18,283,97.000000
28,74715,392594,House,48,300.000000,3234.346906,316.578469,65.741144,10,2,30,0,0,26,106,94.000000
29,74959,395864,Townhouse,96,665.000000,3234.346906,0.000000,30.000000,0,2,31,21,51,76,351,99.000000
30,76867,410806,Apartment,84,559.000000,3234.346906,316.578469,65.741144,20,2,7,30,57,82,172,97.000000
31,78143,419767,Townhouse,98,600.000000,3234.346906,0.000000,20.000000,20,2,7,14,37,67,340,95.000000
32,80986,50121,Apartment,119,1043.000000,3612.000000,450.000000,100.000000,28,3,28,9,10,28,303,86.000000
33,86369,246509,Apartment,109,700.000000,1900.000000,500.000000,80.000000,25,21,130,10,10,13,180,100.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22865,30575199,185076876,House,228,906.976228,3234.346906,800.000000,165.000000,30,2,60,27,57,87,87,94.182791
22866,30576948,27396677,House,80,906.976228,3234.346906,0.000000,0.000000,20,1,1125,3,33,63,114,94.182791
22867,30577049,217343588,Apartment,138,906.976228,3234.346906,200.000000,69.000000,20,1,1125,27,54,84,174,94.182791
22868,30577491,39185276,Townhouse,50,906.976228,3234.346906,316.578469,65.741144,0,3,1125,6,36,66,156,94.182791
22869,30577799,39420239,Apartment,58,906.976228,3234.346906,316.578469,65.741144,0,3,1125,21,51,81,171,94.182791
22870,30578011,39420239,Apartment,76,906.976228,3234.346906,316.578469,65.741144,0,3,1125,10,40,70,160,94.182791
22871,30578581,23405787,House,169,906.976228,3234.346906,500.000000,90.000000,25,2,1125,30,60,90,365,94.182791
22872,30578762,212741130,Apartment,148,906.976228,3234.346906,350.000000,90.000000,25,1,1125,28,58,88,88,94.182791
22873,30578960,126914673,House,30,906.976228,3234.346906,316.578469,65.741144,0,7,1125,22,52,82,82,94.182791
22874,30579138,229390285,House,40,906.976228,3234.346906,316.578469,65.741144,0,1,1125,22,52,82,172,94.182791
22875,30582317,127991555,Apartment,61,906.976228,3234.346906,316.578469,29.000000,0,2,1125,10,10,10,10,94.182791
22876,30587155,61455951,House,69,906.976228,3234.346906,316.578469,65.741144,0,1,1125,25,55,85,175,94.182791
22877,30588253,225492121,Apartment,64,906.976228,3234.346906,250.000000,18.000000,15,2,4,22,52,82,82,94.182791
22878,30589214,191529248,Townhouse,198,906.976228,3234.346906,316.578469,65.741144,0,2,1125,13,20,50,50,94.182791
22879,30589523,69874002,Townhouse,43,906.976228,3234.346906,316.578469,50.000000,0,4,1125,3,3,3,3,94.182791
22880,30590069,179249614,Apartment,71,906.976228,3234.346906,316.578469,65.741144,0,1,1125,12,42,72,162,94.182791
22881,30590430,9020997,House,79,906.976228,3234.346906,500.000000,0.000000,20,1,1125,27,56,56,56,94.182791
22882,30590506,894925,Apartment,84,906.976228,3234.346906,0.000000,30.000000,10,2,1125,27,41,71,346,94.182791
22883,30590632,44912736,House,114,906.976228,3234.346906,316.578469,65.741144,0,1,1125,5,35,65,340,94.182791
22884,30590791,115126017,Apartment,75,906.976228,3234.346906,138.000000,15.000000,0,1,1125,23,48,74,74,94.182791
22885,30591274,229470515,House,50,906.976228,3234.346906,316.578469,65.741144,0,1,1125,14,44,74,164,94.182791
22886,30591343,9020997,House,79,906.976228,3234.346906,500.000000,0.000000,20,1,1125,27,56,56,56,94.182791
22887,30591408,154630235,Serviced apartment,127,906.976228,3234.346906,300.000000,55.000000,20,3,31,25,25,25,25,94.182791
22888,30592088,92403349,Apartment,84,906.976228,3234.346906,316.578469,65.741144,0,1,12,20,41,62,62,94.182791
22889,30592128,26129617,Apartment,30,906.976228,3234.346906,316.578469,0.000000,0,2,1125,29,29,29,29,94.182791
22890,30592332,229206629,Apartment,55,906.976228,3234.346906,316.578469,65.741144,0,1,90,22,52,82,82,94.182791
22891,30592345,150660631,House,129,906.976228,3234.346906,316.578469,65.741144,0,1,1125,30,60,90,365,94.182791
22892,30592362,130394565,Guesthouse,53,906.976228,3234.346906,316.578469,65.741144,0,3,1125,0,5,15,15,94.182791
22893,30592590,22630928,Apartment,130,906.976228,3234.346906,250.000000,130.000000,0,7,750,14,44,74,349,94.182791
22894,30593623,38305445,Apartment,179,906.976228,3234.346906,316.578469,65.741144,0,1,14,15,44,68,68,94.182791